# Generated by Django 3.1.5 on 2022-03-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roomAccessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
                ('user_num', models.IntegerField(default=0)),
                ('entered_or_left', models.IntegerField(default=0)),
                ('entered_or_left_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
