# Generated by Django 3.1.5 on 2022-05-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_access_system', '0003_numberofpeopledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberofpeopledata',
            name='room_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roomaccessdata',
            name='room_name',
            field=models.CharField(max_length=50),
        ),
    ]
